/**
 * Myora – API Type Definitions (extracted from api.ts)
 *
 * Import types from '@/lib/api-types' for modular access.
 * API objects (authAPI, healthAPI, etc.) remain in '@/lib/api'.
 */

export type {
  AuthUser,
  AuthResponse,
  ProfileUpdateData,
  DailyHealthLog,
  DailyLogUpdateData,
  FoodEntry,
  FoodEntryCreateData,
  FoodAnalysisResult,
  ActivityEntry,
  ActivityCreateData,
  FastingLog,
  FastingStartData,
  BloodTest,
  BloodTestResult,
  BloodTestUploadData,
  HealthDocument,
  DocumentUploadData,
  MedicalPhoto,
  MedicalPhotoUploadData,
  VoiceEntry,
  VoiceEntryCreateData,
  UserGoal,
  GoalCreateData,
  GoalUpdateData,
  Achievement,
  UserAchievement,
  UserStreak,
  ChatConversation,
  ChatMessage,
  ConversationCreateData,
  HealthProfile,
  Supplement,
  SupplementRecommendation,
  SupplementOrder,
  OrderCreateData,
  CommunityPost,
  CommunityComment,
  PostCreateData,
  CommentCreateData,
  FamilyMember,
  FamilyMemberCreateData,
  FamilyMedication,
  MedicationCreateData,
  MedicationLog,
  MedicationLogData,
  AdherenceData,
  WearableDevice,
  UserDevice,
  DeviceConnectData,
  WearableDataEntry,
  WearableSyncData,
  SmartNotification,
  SmartNotificationResponse,
} from './api';
