import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'tr';

const translations = {
  en: {
    // Food Capture
    foodAnalysis: 'Food Analysis',
    takePictureToLearnNutrition: 'Take a picture to learn nutritional values',
    cameraReady: 'Camera ready!',
    cameraError: 'Camera error',
    clickToStartCamera: 'Click the button to start the camera',
    analyzingMeal: 'Analyzing your meal...',
    aiIdentifyingFood: 'AI is identifying food items and calculating nutrition',
    analysisComplete: 'Analysis Complete!',
    confident: 'confident',
    caloriesPerServing: 'calories per serving',
    nutritionalValues: 'Nutritional Values',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    retake: 'Retake',
    confirmAndSave: 'Confirm & Save',
    startCamera: 'Start Camera',
    addedToLog: 'added to your log!',
    analysisFailedError: 'Analysis failed',
    identified: 'Identified',
    gallery: 'Gallery',
    analysisFailed: 'Analysis failed',
    retakePhoto: 'Retake',
    retryAnalysis: 'Retry',
    cameraPermDenied: 'Camera permission denied. You can grant access from settings.',
    cameraErrorRetry: 'Camera error. Please try again.',
    galleryPermDenied: 'Gallery permission denied. You can grant access from settings.',
    saveError: 'Save error',

    // App Shell
    log: 'Log',
    coach: 'Coach',
    analysis: 'Analysis',
    quickAdd: 'Quick Add',
    chooseNewEntry: 'Choose a new entry',
    scanFood: 'Scan Food',
    uploadDocuments: 'Upload Documents',
    logActivity: 'Log Activity',
    scanFoodDesc: 'Analyze nutrition and macros from a photo',
    voiceLogDesc: 'Daily voice notes and symptom logging',
    uploadDocumentsDesc: 'Upload lab reports and medical records',
    logActivityDesc: 'Track workouts and physical activity',

    // Home dashboard extended
    today: 'Today',
    yesterday: 'Yesterday',
    healthScoreTitle: 'My Score',
    statusVeryGood: 'Excellent',
    statusGood: 'Good',
    statusImprove: 'Needs improvement',
    statusLow: 'Low',
    hintVeryGood: 'Great momentum — keep pushing today!',
    hintGood: 'You are doing well. A few tweaks can boost your score.',
    hintImprove: 'A few focused actions today can improve your score.',
    hintLow: 'Start with water and protein balance first.',
    waterLabel: 'Water',
    activityLabel: 'Activity',
    nutritionLabel: 'Nutrition',
    consistencyLabel: 'Consistency',
    greeting: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    contextHintAllDone: '🎉 All daily quests complete — amazing day!',
    contextHintBreakfast: '🍳 Time for breakfast — log your first meal!',
    contextHintLunch: '🥗 Lunch time — haven\'t logged anything yet.',
    contextHintActivity: '🏃 No activity yet — even a short walk counts!',
    contextHintStreak: '🔥 {{n}}-day streak — keep it going!',
    scoreBreakdown: 'Score Breakdown',
    focusOn: 'Focus on this',
    scorePotential: 'Improve {{cat}} → could reach {{n}}',
    scoreTip: 'If you reach your {{category}} goal today, your score could rise to {{potential}}.',
    tapForDetails: 'Tap for details',
    streak: 'Streak',
    days: 'days',
    bestStreak: 'Best',
    streakRescueTitle: '🔥 Don\'t break your streak!',
    streakRescueBody: '{{n}}-day streak at risk — log something before midnight!',
    streakRescueWaterTitle: '💧 Haven\'t hit your water goal yet?',
    streakRescueWaterBody: 'A glass of water before bed is an easy way to keep your {{n}}-day streak — and your body — happy!',
    streakRescueSuppLine: 'P.S. Don\'t forget any evening medications, supplements, or vitamins 💊',
    waterLogFailed: 'Could not update water intake',
    foodLabel: 'food',
    displayNamePlaceholder: 'Your name',
    questCelebrationTitle: 'All Quests Done! 🏆',
    questCelebrationBody: 'You\'ve hit every goal today. Amazing work! 🌟',
    chatStarterWater: 'How much water should I drink daily?',
    chatStarterProtein: 'What are good high-protein foods?',
    chatStarterCalories: 'How many calories do I need?',
    chatStarterSleep: 'How does sleep affect weight loss?',
    chatStarterFast: 'What are the benefits of intermittent fasting?',
    nudgeBreakfast: 'Breakfast time — log your first meal of the day!',
    nudgeLunch: 'Lunch time — don\'t forget to log!',
    nudgeDinner: 'Dinner time — log your evening meal.',
    nudgeActivity: 'No activity logged yet — add a workout or walk!',
    profileNudgeTitle: 'Complete your profile',
    profileNudgeBody: 'Add your height & weight for more accurate health insights.',
    profileNudgeAction: 'Complete now',
    dailyQuests: 'Daily Quests',
    questLogMeal: 'Log a meal',
    questDrinkWater: 'Drink 8 glasses of water',
    questDoActivity: 'Do an activity',
    questVoiceLog: 'Record a voice log',
    questCheckScore: 'Check your health score',
    questsCompleted: 'All quests completed!',
    questDataLoadFailed: 'Could not load quest data',
    aiCoachTitle: 'Myora AI Coach',
    aiCoachAsk: 'Ask a question',
    aiCoachHint: 'I can help with nutrition, exercise, and health advice.',
    askAiDesc: 'Get instant answers from your AI health coach',
    achievementEarned: 'Achievement unlocked!',
    achievementsTitle: 'Achievements',
    achievementsEarned: 'Earned',
    achievementsLocked: 'Locked',
    achievementsPoints: 'pts',
    widgetsTitle: 'Widgets',
    activeWidgetCount: 'Active widget count',
    activeWidgetsOnHome: 'widgets active on home',
    createNewWidget: 'Create New Widget',
    dailyRecommendations: 'Daily Recommendations',
    calorieBalance: 'Calorie balance',
    calorieBalanceDesc: 'About {{remainingCalories}} kcal remaining to reach your daily target.',
    waterGoal: 'Water target',
    waterGoalDesc: 'You are at {{waterProgress}}%. Add 1-2 glasses this evening.',
    waterGlassesUnit: 'glasses',
    addWaterGlass: '+ 1 glass (300 ml)',
    waterGoalReached: 'Goal reached! Keep it up 💧',
    proteinTracking: 'Protein tracking',
    proteinTrackingDesc: 'You completed {{proteinProgress}}% of your protein goal.',
    healthTracking: 'Health Tracking',
    devices: 'Devices',
    connectWearables: 'Connect wearables',
    fasting: 'Fasting',
    trackIntermittent: 'Track intermittent',
    mealEntry: 'Meal Entry',
    foodLog: 'Food',

    // Logger
    loggerTitle: 'Logs',
    loggerSubtitle: 'Track recent entries here. Use + below to add a new one.',
    todayLoggingProgress: "Today's Logging Progress",
    mealsLogged: 'Meals',
    voiceEntries: 'Voice',
    activityLogged: 'Activity',
    documents: 'Docs',
    recentEntries: 'Recent Entries',
    recentFoodsTitle: 'Log Again',
    logAgain: 'Log',
    foodRelogged: 'Meal logged again!',
    relogFailed: 'Could not re-log meal',
    justNow: 'Just now',
    minAgo: 'min ago',
    hrAgo: 'hr ago',
    dayAgo: 'd ago',
    min: 'min',
    voiceEntry: 'Voice entry',
    todayCalories: "Today's calories",
    totalEntries: 'entries',
    dataLoadFailed: 'Could not load data',
    entriesLoadFailed: 'Could not load entries',

    // Coach hub
    coachTitle: 'Coach',
    coachSubtitle: 'AI powered guidance center',
    expertChat: 'Expert Chat',
    expertChatDesc: 'Get personalized health guidance grounded in scientific sources.',
    boostDesc: 'See fast improvements and motivational suggestions from daily data.',
    boost: 'Boost',

    // Analysis hub
    analysisTitle: 'Analysis',
    analysisSubtitle: 'Access all insights and modules in one place',
    insights: 'Insights',
    ecosystem: 'Ecosystem',
    healthProfile: 'My Health Profile',
    healthProfileDesc: 'AI score, BMI/BMR/TDEE and personal plans',
    wearableData: 'Wearable Data',
    wearableDataDesc: 'Heart rate, sleep, steps and trends',
    analyticsDesc: 'Weekly/monthly progress charts',
    supplementStore: 'Supplement Store',
    supplementStoreDesc: 'AI recommendations and orders',
    community: 'Community',
    communityDesc: 'Experience sharing and Q&A',
    familyTracking: 'Family Tracking',
    familyTrackingDesc: 'Medication/supplement tracking for relatives',

    // Auth extended
    authSubtitle: 'Start tracking your healthy life',
    signInError: 'Sign In Error',
    signUpError: 'Sign Up Error',
    passwordMismatch: 'Passwords do not match',
    accountCreated: 'Your account was created! Please check your email.',
    loginSuccess: 'You signed in successfully!',
    passwordRepeat: 'Repeat Password',
    exampleEmail: 'example@email.com',
    passwordHint: 'At least 6 characters, 1 letter and 1 number',

    // Dashboard
    dashboard: 'Dashboard',
    dailyGoals: 'Daily Goals',
    calories: 'Calories',
    remaining: 'remaining',
    protein_intake: 'Protein',
    water: 'Water',
    quickActions: 'Quick Actions',
    logFood: 'Log Food',
    addMeal: 'Add Meal',
    recordActivity: 'Record Activity',

    voiceLog: 'Voice Log',
    recentActivities: 'Recent Activities',
    noRecentEntries: 'No recent entries',

    // Navigation
    home: 'Home',
    profile: 'Profile',
    analytics: 'Analytics',
    settings: 'Settings',
    mainNavigation: 'Main navigation',
    quickAddLabel: 'Quick add',

    // Auth
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signOut: 'Sign Out',
    signOutFailed: 'Sign out failed',

    // Onboarding
    onboardingWelcome: 'Welcome to Myora!',
    onboardingWelcomeDesc: "Let's personalize your health journey in a few quick steps.",
    onboardingFeature1: 'AI-Powered Insights',
    onboardingFeature1Desc: 'Get personalized health recommendations powered by AI.',
    onboardingFeature2: 'Track Everything',
    onboardingFeature2Desc: 'Nutrition, activity, sleep and more — all in one place.',
    onboardingFeature3: 'Achieve Your Goals',
    onboardingFeature3Desc: 'Set targets and watch your progress grow every day.',
    onboardingStep1Title: 'About You',
    onboardingStep1Desc: 'Basic info helps us calculate your health metrics.',
    onboardingGender: 'Gender',
    onboardingMale: 'Male',
    onboardingFemale: 'Female',
    onboardingOther: 'Other',
    onboardingHeight: 'Height (cm)',
    onboardingWeight: 'Weight (kg)',
    onboardingBirthDate: 'Date of Birth',
    onboardingStep2Title: 'Your Goal',
    onboardingStep2Desc: 'What do you want to focus on?',
    onboardingGoalWeightLoss: 'Lose Weight',
    onboardingGoalMuscle: 'Build Muscle',
    onboardingGoalHealth: 'Stay Healthy',
    onboardingGoalSleep: 'Better Sleep',
    onboardingGoalStress: 'Reduce Stress',
    onboardingStep3Title: 'Activity Level',
    onboardingStep3Desc: 'How active are you on a typical day?',
    onboardingActivitySedentary: 'Sedentary',
    onboardingActivitySedentaryDesc: 'Mostly sitting (office work)',
    onboardingActivityLight: 'Lightly Active',
    onboardingActivityLightDesc: 'Light exercise 1-3 days/week',
    onboardingActivityModerate: 'Moderately Active',
    onboardingActivityModerateDesc: 'Moderate exercise 3-5 days/week',
    onboardingActivityVery: 'Very Active',
    onboardingActivityVeryDesc: 'Hard exercise 6-7 days/week',
    onboardingNext: 'Next',
    onboardingBack: 'Back',
    onboardingFinish: 'Get Started',
    onboardingSkip: 'Skip for now',
    onboardingStepOf: 'of',

    // General
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    add: 'Add',
    adding: 'Adding...',
    remove: 'Remove',

    // NotFound
    pageNotFound: 'This page was not found.',
    goHome: 'Go to Home',

    // AppLayout
    exitAppConfirm: 'Do you want to exit the app?',

    // Activity Logger
    activityLogTitle: 'Log Activity',
    activityLogSubtitle: 'Track your workouts and physical activities',
    newActivity: 'New Activity',
    activityType: 'Activity Type',
    selectActivityType: 'Select activity type',
    durationMinutes: 'Duration (minutes)',
    intensity: 'Intensity',
    selectIntensity: 'Select intensity level',
    intensityLow: 'Low',
    intensityModerate: 'Moderate',
    intensityHigh: 'High',
    estimatedCalories: 'Estimated Calories Burned (optional)',
    notesOptional: 'Notes (optional)',
    notesPlaceholder: 'How did you feel? Any observations...',
    saving: 'Saving...',
    todaysActivities: "Today's Activities",
    loadingActivities: 'Loading activities...',
    noActivitiesYet: 'No activities logged yet',
    logFirstActivity: 'Log your first activity above',
    loggedSuccessfully: 'logged successfully!',
    minutes: 'minutes',
    intensityLabel: 'intensity',
    activityTypeRequired: 'Please select activity type',
    durationMinError: 'Duration must be at least 1 minute',

    // Blood Test Analysis
    bloodTest: 'Blood Test',
    analyzeWithAi: 'Analyze your results with AI',
    upload: 'Upload',
    uploadNewTest: 'Upload New Test',
    labNamePlaceholder: 'Lab name',
    testResultsPlaceholder: 'Paste test results or enter OCR text...\nExample:\nGlucose: 95 mg/dL\nHbA1c: 5.4%\nTSH: 2.1 mIU/L',
    analyzing: 'Analyzing...',
    analyze: 'Analyze',
    noBloodTestsYet: 'No blood tests yet',
    uploadTestsForAi: 'Upload your test results for AI analysis',
    uploadTest: 'Upload Test',
    statusNormal: 'Normal',
    statusAttention: 'Attention',
    statusCritical: 'Critical',
    statusHigh: 'High',
    aiSummary: 'AI Summary',
    ref: 'Ref',
    bloodTestUploaded: 'Blood test uploaded successfully',
    bloodTestUploadFailed: 'Could not upload blood test',
    bloodTestsLoadFailed: 'Could not load blood tests',

    // Community
    communityTitle: 'Community',
    communitySubtitle: 'Share experiences, grow together',
    share: 'Share',
    catGeneral: 'General',
    catNutrition: 'Nutrition',
    catExercise: 'Exercise',
    catQuestions: 'Questions',
    catSuccessStories: 'Success Stories',
    newPost: 'New Post',
    titlePlaceholder: 'Title',
    shareThoughts: 'Share your thoughts...',
    sharing: 'Sharing...',
    anonymous: 'Anonymous',
    noPostsYet: 'No posts yet',
    beFirstToPost: 'Be the first to post!',
    postCreated: 'Post created',
    postCreateFailed: 'Could not create post',
    postsLoadFailed: 'Could not load posts',
    likeFailed: 'Like action failed',

    // Analytics
    statsAndAnalysis: 'Statistics & Analysis',
    detailedProgress: 'Detailed progress tracking and analysis',
    weeklyLog: 'Weekly Log',
    last7Days: 'Last 7 days',
    achievementCount: 'Achievement',
    fastingDay: 'Fasting Day',
    thisMonth: 'This Month',
    avgCalories: 'Avg. Calories',
    daily: 'Daily',
    weeklyTrend: 'Weekly Trend',
    macroDistribution: 'Macro Distribution',
    monthlyProgressTitle: 'Monthly Progress',
    achievementsSection: 'Achievements',
    notEnoughData: 'Not enough data yet',
    noFoodRecords: 'No food records found',
    noFastingRecords: 'No fasting records yet',
    noAchievementDef: 'No achievement definitions found',
    completed: 'Completed',
    proteinMacro: 'Protein',
    carbsMacro: 'Carbs',
    fatMacro: 'Fat',
    dayNames: 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    monthNames: 'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',

    // Expert Chat
    expertTitle: 'Expert',
    expertSubtitle: 'Your health advisor based on scientific sources',
    welcomeMessage: "Hello! I'm Expert, your health advisor. I'm here to provide personalized health information based on scientific sources. How can I help you?",
    errorFallback: 'Sorry, I could not generate a response right now. Please try again.',
    sources: 'Sources',
    askHealthQuestion: 'Ask a health question...',
    expertDisclaimer: 'Expert provides information based on scientific publications. It does not replace medical advice.',

    // Voice Logger
    voiceRecording: 'Voice Recording',
    voiceRecordSubtitle: 'Record your health notes or meals with voice',
    healthLog: 'Health Log',
    foodRecord: 'Food Record',
    recordingDone: 'Recording done!',
    recordingStarted: 'Recording started!',
    micDenied: 'Microphone access denied. Please grant microphone permission and try again.',
    micNotAccessible: 'Could not access microphone',
    playbackFailed: 'Could not play recording',
    textNeeded: 'Text needed for analysis. Please speak or type.',
    voiceFoodEntry: 'Voice Food Entry',
    voiceHealthLog: 'Voice Health Log',
    foodsAddedToLog: 'foods added to calorie tracking!',
    analysisDoneAndSaved: 'Analysis completed and saved!',
    savedWithError: 'Recording saved (AI analysis server error)',
    enterText: 'Please enter text',
    recordingInProgress: 'Recording in progress...',
    recordingSaving: 'Saving...',
    foodRecordPrompt: 'Tell what you ate today, e.g. "I had chicken rice for lunch"',
    healthRecordPrompt: 'Share how you feel today, your health thoughts',
    recordCompleteTime: 'Recording done',
    foodAnalyzeHint: 'Click Analyze, your food will be auto-detected and saved',
    healthAnalyzeHint: 'Listen or analyze',
    recordFoodVoice: 'Record meals with voice',
    readyToListen: 'Ready to listen',
    foodVoiceDesc: 'Instead of taking photos, just tell your meals by voice',
    healthVoiceDesc: 'Tap the microphone to start your daily health log',
    speechNotSupported: 'Your browser does not support speech recognition. You can type after recording.',
    recordFoodBtn: 'Record Food',
    startRecordingBtn: 'Start Recording',
    typeInstead: 'Type Instead',
    stopRecordingBtn: 'Stop Recording',
    play: 'Play',
    analyzeBtn: 'Analyze',
    typeYourFood: 'Type Your Food',
    typeYourNote: 'Type Your Health Note',
    foodTypePlaceholder: 'E.g. I had chicken rice for lunch with salad and ayran',
    healthTypePlaceholder: 'E.g. I feel tired today, my sleep quality was poor...',
    analyzeAndSave: 'Analyze & Save',
    liveTranscription: 'Live Transcription',
    speechNotAvailable: 'Speech recognition not available. You can also type your recording:',
    typeRecording: 'Type your recording here...',
    detectingFood: 'Detecting food...',
    analyzingHealthLog: 'Analyzing your health log...',
    foodDetectDesc: 'Food from your voice is being identified and calories calculated',
    healthAnalyzeDesc: 'AI is processing your health info',
    audioRecording: 'Audio Recording',
    aiAnalysisResults: 'AI Analysis Results',
    moodLabel: 'Mood:',
    emotionLabel: 'Emotion:',
    keyTopics: 'Key topics:',
    summaryLabel: 'Summary:',
    recommendationsTitle: 'Recommendations',
    newRecording: 'New Recording',
    neutral: 'Neutral',

    // Interval Fasting
    intermittentFasting: 'Intermittent Fasting',
    fastingSubtitle: 'Fasting tracking for a healthy life',
    currentFast: 'Current Fast',
    dayStreak: 'day streak',
    timeRemaining: 'time remaining',
    fastingComplete: 'completed!',
    progress: 'Progress',
    startFast: 'Start Fast',
    pauseFast: 'Pause',
    resumeFast: 'Resume',
    endFast: 'End',
    fastingActive: 'Fasting active - Keep going!',
    fastingChipLabel: 'Fasting',
    weeklySummaryTitle: '📊 Last Week\'s Summary',
    weeklySummaryMeals: 'Avg kcal/day',
    weeklySummaryActivities: 'Active days',
    weeklySummaryAvgWater: 'Avg glasses/day',
    weeklySummaryOver: 'Across {{n}} days',
    fastingPlans: 'Fasting Plans',
    fastingPlanBeginner: 'Ideal for beginners',
    fastingPlanIntermediate: 'Intermediate',
    fastingPlanPopular: 'Most popular',
    fastingPlanAdvanced: 'Advanced',
    fastingPlanExpert: 'Expert level',
    todayBenefits: "Today's Benefits",
    fatBurning: 'Fat Burning',
    metabolismBoosted: 'Metabolism boosted',
    detox: 'Detox',
    cellsRenewing: 'Cells renewing',
    focus: 'Focus',
    mentalClarity: 'Mental clarity increasing',
    fastingCongrats: 'Congratulations! You completed your fasting goal!',
    fastingStarted: 'Fasting started! Good luck',
    fastingStartFailed: 'Could not start fasting',
    fastingPaused: 'Fasting paused',
    fastingReset: 'Fasting reset',

    // Wearable Devices
    wearableDevicesTitle: 'Wearable Devices',
    wearableDevicesSubtitle: 'Track your health data',
    bluetoothNote: 'Bluetooth device sync coming soon. Device management and data viewing is currently active.',
    addDevice: 'Add Device',
    addNewDevice: 'Add New Device',
    connectSmartwatch: 'Connect your smartwatch or fitness tracker',
    selectDevice: 'Select Device',
    selectDevicePlaceholder: 'Select a device',
    deviceName: 'Device Name',
    deviceNamePlaceholder: 'E.g. My Watch',
    connectDevice: 'Connect Device',
    noDevicesYet: 'No devices connected yet',
    addDeviceToTrack: 'Add a device to track your health data',
    connected: 'Connected',
    notConnected: 'Not Connected',
    disconnect: 'Disconnect',
    connect: 'Connect',
    deviceSelectAndName: 'Please select a device and enter a name',
    deviceAdded: 'Device added successfully',
    deviceAddFailed: 'Error adding device',
    deviceConnected: 'Device connected',
    deviceDisconnected: 'Device disconnected',
    connectionUpdateFailed: 'Could not update connection status',
    deviceRemoved: 'Device removed',
    deviceRemoveFailed: 'Error removing device',

    // Supplement Store
    supplementTitle: 'Supplements',
    supplementSubtitle: 'Personalized recommendations & orders',
    recommendationsTab: 'Recommendations',
    storeTab: 'Store',
    ordersTab: 'Orders',
    noRecommendationsYet: 'No recommendations yet',
    recommendationsDesc: 'Recommendations will be generated when your blood test or health profile is analyzed',
    highPriority: 'High',
    mediumPriority: 'Medium',
    lowPriority: 'Low',
    priority: 'Priority',
    dosage: 'Dosage:',
    all: 'All',
    orderNow: 'Order Now',
    noCategoryProducts: 'No products in this category yet',
    noOrdersYet: 'No orders yet',
    recStatusUpdated: 'Recommendation status updated',
    recStatusFailed: 'Could not update recommendation status',
    recsLoadFailed: 'Could not load recommendations',
    catVitamins: 'Vitamins',
    catMinerals: 'Minerals',
    catAminoAcids: 'Amino Acids',
    catHerbal: 'Herbal',
    catProbiotics: 'Probiotics',
    catOmega: 'Omega',
    catProtein: 'Protein',

    // Family Tracking
    familyTrackingTitle: 'Family Tracking',
    familyTrackingSubtitleHeader: 'Track the health of your loved ones',
    medicationTracking: 'Medication tracking',
    familyMember: 'Family Member',
    noFamilyMembers: 'No family members yet',
    addFamilyDesc: 'Add your loved ones to track their health',
    addFamilyMember: 'Add Family Member',
    name: 'Name',
    todayAdherence: "Today's Adherence",
    medicationsTaken: 'medications taken',
    medicationsAndSupplements: 'Medications & Supplements',
    noMedicationsYet: 'No medications added yet',
    addMedicationDesc: 'Start tracking by adding medications and supplements',
    addMedication: 'Add Medication',
    medicationName: 'Medication/Supplement name',
    addMedicationSupplement: 'Add Medication/Supplement',
    relParent: 'Parent',
    relChild: 'Child',
    relSpouse: 'Spouse',
    relSibling: 'Sibling',
    relGrandparent: 'Grandparent',
    relOther: 'Other',
    familyMemberAdded: 'Family member added',
    familyMemberAddFailed: 'Could not add family member',
    familyLoadFailed: 'Could not load family members',
    medicationAdded: 'Medication added',
    medicationAddFailed: 'Could not add medication',
    medicationLogFailed: 'Medication log failed',

    // User Profile
    profileInfo: 'Profile Information',
    displayName: 'Display Name',
    yourName: 'Your name',
    dateOfBirth: 'Date of Birth',
    heightCm: 'Height (cm)',
    weightKg: 'Weight (kg)',
    activityLevel: 'Activity Level',
    selectActivityLevel: 'Select your activity level',
    sedentary: 'Sedentary',
    lightlyActive: 'Lightly Active',
    moderatelyActive: 'Moderately Active',
    active: 'Active',
    veryActive: 'Very Active',
    bmi: 'Body Mass Index (BMI)',
    bmiUnderweight: 'Underweight',
    bmiNormal: 'Normal',
    bmiOverweight: 'Overweight',
    bmiObese: 'Obese',
    profileUpdated: 'Your profile has been updated',
    profileUpdateFailed: 'Error updating profile',
    signOutLabel: 'Sign Out',
    signOutError: 'Error signing out',

    // SupplementTracker
    stSupplementMarked: 'Supplement marked as taken',
    stMarkFailed: 'Failed to mark supplement',
    stUnmarked: 'Mark removed',
    stActionFailed: 'Action failed',
    stAllTaken: 'All supplements taken!',
    stTakenCount: 'supplements taken',
    stAllTakenDesc: 'All your supplements for today are done, great!',
    stMarkRemaining: 'Mark the ones you haven\'t taken',
    stLast7Days: 'Last 7 days',
    stLast30Days: 'Last 30 days',
    stConsistency: 'Consistency',
    stLast30DaysTitle: 'Last 30 Days',
    stTaken: 'Taken',
    stNotTaken: 'Not taken',
    stToday: 'Today',
    stRemoveTracking: 'Remove Tracking',

    // HealthProfile
    hpTitle: 'My Health Profile',
    hpSubtitle: 'AI-powered personal health analysis',
    hpCalculating: 'Calculating...',
    hpUpdate: 'Update',
    hpLoadFailed: 'Could not load health profile',
    hpNotCreated: 'Your health profile has not been created yet',
    hpCreateDesc: 'Let us create your personalized health profile by analyzing your data',
    hpCreating: 'Creating...',
    hpCreateProfile: 'Create Profile',
    hpOverallScore: 'Overall Health Score',
    hpAiAssessment: 'AI Assessment',
    hpStrengths: 'Your Strengths',
    hpImprovementAreas: 'Improvement Areas',
    hpNutritionPlan: 'Nutrition Plan',
    hpDailyCalories: 'Daily Calories:',
    hpExercisePlan: 'Exercise Plan',
    hpSupplementRecs: 'Supplement Recommendations',
    hpLastUpdate: 'Last update:',
    hpUpdated: 'Health profile updated',
    hpCreateFailed: 'Could not create health profile',
    hpSessionExpired: 'Session may have expired. Please reopen the app.',

    // DocumentUpload
    docTitle: 'Health Documents',
    docSubtitle: 'Upload your health documents and get AI analysis recommendations',
    docUploading: 'Uploading...',
    docDropHere: 'Drop the file here',
    docUploadTitle: 'Upload Health Document',
    docUploadDesc: 'Blood tests, lab reports, prescriptions, medical images',
    docSelectFile: 'Select File',
    docImages: 'Images',
    docSpreadsheets: 'Spreadsheets',
    docSupportedTypes: 'Supported Documents',
    docBloodTest: 'Blood Test',
    docThyroid: 'Thyroid Function',
    docCholesterol: 'Cholesterol Report',
    docAllergy: 'Allergy Test',
    docPrescription: 'Prescription',
    docMedicalImage: 'Medical Image',
    docVaccination: 'Vaccination Record',
    docFitness: 'Fitness Assessment',
    docLoadingDocs: 'Loading documents...',
    docYourDocs: 'Your Documents',
    docNoDocs: 'No documents uploaded yet',
    docUploadFirst: 'Upload a health document above',
    docDetailedAnalysis: 'Detailed Analysis:',
    docAiAnalysis: 'AI-powered health document analysis',
    docInfo: 'Document Info',
    docType: 'Document Type',
    docUploadDate: 'Upload Date',
    docFileSize: 'File Size',
    docFormat: 'Format',
    docAiSummary: 'AI Analysis Summary',
    docRecommendations: 'Recommendations',
    docTags: 'Tags',
    docAnalysisComplete: 'Document analysis completed!',
    docUnsupportedFormat: 'Unsupported file format',
    docTooLarge: 'File too large. Maximum 10MB.',
    docStillProcessing: 'Document is still being processed. Please wait.',
    docAnalysisFailed: 'Document analysis failed. Please try uploading again.',
    docNotAnalyzed: 'Document has not been analyzed yet.',
    docAnalyzed: 'Analyzed',
    docProcessing: 'Processing',

    // MedicalPhotoAnalysis
    mpTitle: 'Smart Medical Photo Analysis',
    mpSubtitle: 'Take a photo, AI will automatically detect and analyze it',
    mpSupportedTypes: 'Supported Analysis Types',
    mpUrineAnalysis: 'Urine Analysis',
    mpStoolAnalysis: 'Stool Analysis',
    mpTongueAnalysis: 'Tongue Color Analysis',
    mpEyeAnalysis: 'Eye Analysis',
    mpAutoDetectDesc: 'When you take a photo, AI will automatically determine the type and analyze it',
    mpStartCapture: 'Start by taking a medical sample photo',
    mpAutoDetect: 'AI will automatically determine the type and analyze',
    mpAnalyzing: 'AI Analyzing...',
    mpDetectingType: 'Detecting type first...',
    mpUrineInProgress: 'Performing urine analysis',
    mpStoolInProgress: 'Performing stool analysis',
    mpTongueInProgress: 'Performing tongue analysis',
    mpEyeInProgress: 'Performing eye analysis',
    mpGenericInProgress: 'Performing analysis',
    mpUrine: 'Urine',
    mpStool: 'Stool',
    mpTongue: 'Tongue',
    mpEye: 'Eye',
    mpColor: 'Color:',
    mpConsistency: 'Consistency:',
    mpClarity: 'Clarity:',
    mpDetailedResults: 'Detailed Analysis Results',
    mpObservations: 'Observations:',
    mpConcerns: 'Points of Attention:',
    mpRecommendations: 'Recommendations:',
    mpWarningTitle: 'Important Warning:',
    mpWarningText: 'This analysis is for informational purposes only and does not replace a medical examination. If you have serious concerns, please consult a healthcare professional. Expert medical opinion is especially recommended for eye and tongue analyses.',
    mpStartCamera: 'Start Camera',
    mpTakePhoto: 'Take Photo',
    mpRetake: 'Retake',
    mpAnalyze: 'Analyze',
    mpNewAnalysis: 'New Analysis',
    mpSave: 'Save',
    mpAnalysisFailed: 'Analysis failed',
    mpCameraError: 'Cannot access camera',
    mpSaved: 'Medical analysis saved',
    mpConfidence: 'confidence',

    // WearableDataDashboard
    wdTitle: 'Health Data',
    wdSubtitle: 'Data from your wearable devices',
    wdNoData: 'No data yet',
    wdNoDataDesc: 'Connect a wearable device to start tracking your health data.',
    wdHeartRate: 'Heart Rate',
    wdSteps: 'Steps',
    wdCalories: 'Calories',
    wdSleepQuality: 'Sleep Quality',
    wdBloodOxygen: 'Blood Oxygen',
    wdStressLevel: 'Stress Level',
    wdExerciseMinutes: 'Exercise Duration',
    wdVo2Max: 'VO2 Max',
    wdLast12Hours: 'Last 12 hours data',

    // NotificationSettings
    nsTitle: 'Smart Notifications',
    nsSubtitle: 'Duolingo-style personalized health reminders',
    nsPermission: 'Notification Permission',
    nsActive: 'Active',
    nsInactive: 'Inactive',
    nsPermissionDesc: 'Browser permission required for smart notifications. You will receive reminders personalized to your health goals.',
    nsEnable: 'Enable Notifications',
    nsActiveDesc: 'Notifications active! You will receive smart reminders based on your health data.',
    nsTest: 'Test Notification',
    nsSmartNotifications: 'Smart Notifications',
    nsTypes: 'Notification Types',
    nsWaterReminder: 'Water Reminder',
    nsWaterDesc: 'Track your water goals',
    nsWaterExample: '2 more glasses of water needed!',
    nsCalorieReminder: 'Calorie Reminder',
    nsCalorieDesc: 'Complete your daily calorie goal',
    nsCalorieExample: '500 more calories needed',
    nsProteinReminder: 'Protein Reminder',
    nsProteinDesc: 'Reach your protein goal',
    nsProteinExample: '20g more protein needed',
    nsActivityReminder: 'Activity Reminder',
    nsActivityDesc: 'Don\'t forget to move',
    nsActivityExample: 'How about a 10-minute walk?',
    nsMoodLog: 'Mood Log',
    nsMoodDesc: 'Daily mood tracking',
    nsMoodExample: 'Record how you feel today',
    nsHealthCheck: 'Health Check',
    nsHealthCheckDesc: 'Weekly health analysis',
    nsHealthCheckExample: 'Time for weekly health check',
    nsMotivation: 'Motivation Messages',
    nsMotivationDesc: 'Inspiring reminders',
    nsMotivationExample: 'You\'re doing great! Keep going!',
    nsSmartTiming: 'Smart Timing',
    nsSmartTimingDesc: 'Notifications are sent at different times personalized to your health data. No spam!',
    nsEnabled: 'Notifications enabled!',
    nsDenied: 'Notification permission denied',
    nsTestTitle: 'Test Notification',
    nsTestMessage: 'Notifications working! You will now receive health reminders',
    nsTestSent: 'Test notification sent!',
    nsSmartCreated: 'Smart notifications created!',
    nsExample: 'Example:',

    // QuickActions
    qaScanFood: 'Scan Food',
    qaVoiceLog: 'Voice Log',
    qaUploadDocs: 'Upload Health Docs',
    qaLogActivity: 'Log Activity',
    qaViewAll: 'View All Logged Activities',

    // Boost
    boostLoading: 'Analyzing your data...',
    boostSubtitleFull: 'Personal supplement recommendations based on your data',
    boostAnalysisSummary: 'Analysis Summary',
    boostDose: 'Dose:',
    boostTiming: 'Timing:',
    boostEvidence: 'Supporting data:',
    boostTracking: 'Tracking',
    boostStartTracking: 'Start Taking',
    boostCollapse: 'Collapse',
    boostDetails: 'Details',
    boostBloodTestSection: 'Blood Test Based',
    boostUrgentSection: 'Urgent Recommendations',
    boostGeneralSection: 'General Recommendations',
    boostAdditionalSection: 'Additional Recommendations',
    boostDisclaimer: 'These recommendations are based on your nutrition, activity, and blood test data. Please consult your healthcare professional before starting any supplement.',
    boostNutrition: 'Nutrition',
    boostActivity: 'Activity',
    boostWater: 'Water',
    boostBloodTest: 'Blood Test',
    boostNoData: 'no data',
    boostNone: 'none',
    boostMeals7d: 'meals (7 days)',
    boostNoMealData: 'No meal data yet',
    boostMinActivity: 'min activity',
    boostNoActivityData: 'no activity data',
    boostBtAnalyzed: 'blood test analyzed',
    boostDaysAgo: 'days ago',
    boostNoBt: 'no blood test',
    boostSupplements: 'supplement',
    boostRecsCreated: 'recommendations created',
    boostBtBasedCount: 'of them blood test based',
    boostHighPriority: 'High Priority',
    boostMediumPriority: 'Medium Priority',
    boostLowPriority: 'Low Priority',

    // Boost supplement names
    supIronSupplement: 'Iron Supplement',
    supB12Vitamin: 'Vitamin B12',
    supD3Vitamin: 'Vitamin D3',
    supCalciumD3: 'Calcium + D3',
    supOmega3HighDose: 'Omega-3 (High Dose)',
    supIronFolicAcid: 'Iron + Folic Acid',
    supWheyProtein: 'Whey Protein',
    supOmega3FishOil: 'Omega-3 (Fish Oil)',
    supFiber: 'Fiber Supplement (Psyllium)',
    supMagnesium: 'Magnesium',
    supIronB12: 'Iron + B12',
    supCreatine: 'Creatine Monohydrate',
    supElectrolyte: 'Electrolyte Supplement',
    supMagLTheanine: 'Magnesium + L-Theanine',
    supMultivitamin: 'Multivitamin',
    supVitaminC: 'Vitamin C',
    supProbiotic: 'Probiotic',

    // Boost supplement categories
    catBloodTestBased: 'Blood Test Based',
    catNutrientBased: 'Nutrient Based',
    catActivityBased: 'Activity Based',
    catHydration: 'Hydration',
    catSleep: 'Sleep',
    catGeneralHealth: 'General Health',
    catPerformance: 'Performance',
    catDigestion: 'Digestion',

    // Boost supplement reasons
    supIronReason: 'Your blood test shows low iron level ({{value}} {{unit}}). Iron deficiency can cause fatigue, weakness, and concentration problems.',
    supB12Reason: 'Your blood test shows low B12 level ({{value}} {{unit}}). B12 deficiency can lead to nerve damage, anemia, and cognitive issues.',
    supD3BtReason: 'Your blood test shows low vitamin D ({{value}} {{unit}}). Vitamin D is critical for bone health, immune system, and mood.',
    supCalciumReason: 'Your blood test shows low calcium ({{value}} {{unit}}). Calcium supplementation is recommended for bone health and muscle function.',
    supOmega3BtReason: 'Your cholesterol level is high ({{value}} {{unit}}). Omega-3 fatty acids support heart health with triglyceride-lowering effect.',
    supIronHgbReason: 'Hemoglobin is low ({{value}} {{unit}}). Anemia risk present. Iron and folic acid support red blood cell production.',
    supWheyReason: 'You reached {{percent}}% of your daily protein goal ({{amount}}g). Protein supplement is recommended for muscle repair and satiety.',
    supD3NutrientReason: 'Low dairy consumption in the last 7 days. Vitamin D3 is needed for bone health, immune system, and muscle function.',
    supOmega3NutrientReason: 'No fish consumption detected in the last 7 days. Omega-3 fatty acids are important for heart health, joint flexibility, and brain function.',
    supFiberReason: 'Your average daily fiber intake is {{amount}}g. Recommended minimum is 25g. Fiber is needed for digestive health, blood sugar balance, and satiety.',
    supMagnesiumReason: 'Weekly {{minutes}} min activity, {{calories}} kcal burned. Magnesium prevents muscle cramps, improves sleep quality, and supports energy metabolism.',
    supIronB12Reason: 'High running/walking activity. In endurance sports, red blood cell destruction increases from foot strikes. Iron and B12 supplementation is recommended.',
    supCreatineReason: 'You do intense exercise. Creatine is one of the most researched supplements for increasing muscle strength, performance, and recovery.',
    supElectrolyteReason: 'Water intake is at {{percent}}% of your target ({{current}}ml / {{target}}ml). Electrolyte balance is important for hydration, muscle function, and energy.',
    supMagLTheanineReason: 'Your sleep duration is {{hours}} hours {{mins}} min. Magnesium and L-Theanine naturally improve sleep quality.',
    supMultivitaminReason: 'Calorie intake is at {{percent}}% of target. Multivitamin is recommended to prevent micronutrient deficiencies at low calorie intake.',
    supVitaminCReason: 'Low vegetable and fruit consumption in the last 7 days. Vitamin C is important for immune system, skin health, and iron absorption.',
    supProbioticReason: 'Gut health is the foundation of overall health. Probiotics support digestion, immune system, and nutrient absorption.',

    // Boost supplement dosages
    dosIron: '25-50mg elemental iron, once daily',
    dosB12: '1000-2000 mcg, once daily',
    dosD3High: '2000-4000 IU, once daily',
    dosCalciumD3: '500-600mg calcium + 1000 IU D3, once daily',
    dosOmega3High: '2000-3000mg EPA+DHA, 1-2 times daily',
    dosIronFolic: 'Iron 25mg + Folic Acid 400mcg, once daily',
    dosWhey: '25-30g, 1-2 times daily',
    dosD3Low: '1000-2000 IU, once daily',
    dosOmega3: '1000-2000mg EPA+DHA, once daily',
    dosFiber: '5-10g, 1-2 times daily',
    dosMagnesium: '300-400mg (Magnesium Bisglycinate), once daily',
    dosIronB12: 'Iron 18mg + B12 1000mcg, once daily',
    dosCreatine: '3-5g, once daily',
    dosElectrolyte: '1 packet, 1-2 times daily',
    dosMagLTheanine: 'Magnesium 200mg + L-Theanine 200mg',
    dosMultivitamin: '1 tablet, once daily',
    dosVitaminC: '500-1000mg, once daily',
    dosProbiotic: '10-20 billion CFU, once daily',

    // Boost supplement timings
    timIronEmpty: 'On empty stomach, with vitamin C (improves absorption)',
    timMorningAny: 'Morning, on empty or full stomach',
    timMorningFatty: 'Morning, with a fatty meal',
    timWithMeal: 'With a meal',
    timPostWorkout: 'Post-workout or between meals',
    timWithWater: 'With plenty of water, 30 min before meals',
    timEvening: 'Evening, before bed',
    timIronVitC: 'On empty stomach, with vitamin C',
    timPrePostWorkout: 'Pre or post-workout',
    timWithWaterExercise: 'Mixed with water, before/after exercise',
    timBeforeBed: '30-60 min before bed',
    timBreakfast: 'Morning with breakfast',
    timMorningEmpty: 'Morning, on empty stomach',

    // Boost basedOn labels
    boBasedOnBloodTest: 'Blood test:',
    boBasedOnValue: 'Value:',
    boBasedOnDailyProtein: 'Daily protein:',
    boBasedOn7dAvg: '7-day avg:',
    boBasedOn7dAnalysis: '7-day nutrition analysis',
    boBasedOnDairyLow: 'Dairy consumption insufficient',
    boBasedOnNoFish: 'No fish consumption',
    boBasedOn7dFiber: '7-day avg. fiber:',
    boBasedOnFiberTarget: 'Target: 25g/day',
    boBasedOnWeeklyActivity: 'Weekly activity:',
    boBasedOnBurned: 'Burned:',
    boBasedOnRunDetected: 'Running/walking activity detected',
    boBasedOnHighIntensity: 'High-intensity activity detected',
    boBasedOnWaterIntake: 'Water intake:',
    boBasedOnSleepDuration: 'Sleep duration:',
    boBasedOnSleepTarget: 'Target: 7-8 hours',
    boBasedOnDailyCalories: 'Daily calories:',
    boBasedOnTargetRatio: 'Target ratio:',
    boBasedOnVegFruitLow: 'Vegetable/fruit consumption insufficient',
    boBasedOnGeneralHealth: 'General health recommendation',

    // DarkModeToggle
    toggleTheme: 'Toggle theme',
  },
  tr: {
    // Food Capture
    foodAnalysis: 'Yemek Analizi',
    takePictureToLearnNutrition: 'Fotografraf cekerek besin degerlerini ogrenin',
    cameraReady: 'Kamera hazir!',
    cameraError: 'Kamera hatasi',
    clickToStartCamera: 'Kamerayi baslatmak icin butona tiklayin',
    analyzingMeal: 'Yemeginiz analiz ediliyor...',
    aiIdentifyingFood: 'Yapay zeka besin maddelerini tanimliyor ve kalori hesapliyor',
    analysisComplete: 'Analiz Tamamlandi!',
    confident: 'guvenilir',
    caloriesPerServing: 'porsiyon basina kalori',
    nutritionalValues: 'Besin Degerleri',
    protein: 'Protein',
    carbs: 'Karbonhidrat',
    fat: 'Yag',
    retake: 'Tekrar Cek',
    confirmAndSave: 'Onayla & Kaydet',
    startCamera: 'Kamerayi Baslat',
    addedToLog: 'gunlugunuze kaydedildi!',
    analysisFailedError: 'Analiz basarisiz',
    identified: 'Tanimlandi',
    gallery: 'Galeri',
    analysisFailed: 'Analiz basarisiz oldu',
    retakePhoto: 'Tekrar Cek',
    retryAnalysis: 'Tekrar Dene',
    cameraPermDenied: 'Kamera izni reddedildi. Ayarlardan izin verebilirsiniz.',
    cameraErrorRetry: 'Kamera hatasi. Lutfen tekrar deneyin.',
    galleryPermDenied: 'Galeri izni reddedildi. Ayarlardan izin verebilirsiniz.',
    saveError: 'Kayit hatasi',

    // App Shell
    log: 'Kayit',
    coach: 'Koc',
    analysis: 'Analiz',
    quickAdd: 'Hizli Kayit',
    chooseNewEntry: 'Yeni bir giris sec',
    scanFood: 'Yemek Tara',
    uploadDocuments: 'Belge Yukle',
    logActivity: 'Aktivite Kaydet',
    scanFoodDesc: 'Fotograf ile besin ve makro analizi',
    voiceLogDesc: 'Gunluk sesli not ve semptom kaydi',
    uploadDocumentsDesc: 'Tahlil ve rapor yukleme',
    logActivityDesc: 'Antrenman ve aktivite kaydi',

    // Home dashboard extended
    today: 'Bugun',
    yesterday: 'Dun',
    healthScoreTitle: 'My Score',
    statusVeryGood: 'Mukemmel',
    statusGood: 'Iyi',
    statusImprove: 'Gelistirilebilir',
    statusLow: 'Dusuk',
    hintVeryGood: 'Harika gidiyorsun \u2014 bu tempoyu koru!',
    hintGood: 'Iyi gidiyorsun, birkac kucuk dokunusla yukselebilir.',
    hintImprove: 'Bugun birkac adimla skoru toparlayabilirsin.',
    hintLow: 'Once su ve protein dengesini iyilestirerek baslayalim.',
    waterLabel: 'Su',
    activityLabel: 'Aktivite',
    nutritionLabel: 'Beslenme',
    consistencyLabel: 'Tutarlilik',
    greeting: 'Gunaydin',
    greetingAfternoon: 'Iyi gunler',
    greetingEvening: 'Iyi aksamlar',
    contextHintAllDone: '🎉 Tüm günlük görevler tamamlandı — harika gün!',
    contextHintBreakfast: '🍳 Kahvaltı zamanı — ilk öğününü kaydet!',
    contextHintLunch: '🥗 Öğle yemeği vakti — henüz bir şey kaydetmedin.',
    contextHintActivity: '🏃 Henüz aktivite yok — kısa bir yürüyüş bile sayılır!',
    contextHintStreak: '🔥 {{n}} günlük seri — devam et!',
    scoreBreakdown: 'Skor Detayi',
    focusOn: 'Buna odaklan',
    scorePotential: '{{cat}} geliştir → {{n}} olabilir',
    scoreTip: '{{category}} hedefine ulasirsan skorun {{potential}} olabilir.',
    tapForDetails: 'Detaylar icin dokun',
    streak: 'Seri',
    days: 'gun',
    bestStreak: 'En iyi',
    streakRescueTitle: '🔥 Seriyi bozma!',
    streakRescueBody: '{{n}} günlük serin risk altında — gece yarısından önce bir şey kaydet!',
    streakRescueWaterTitle: '💧 Su hedefine ulaşamadın mı?',
    streakRescueWaterBody: 'Yatmadan önce bir bardak su {{n}} günlük serini — ve bedenini — mutlu eder!',
    streakRescueSuppLine: 'Not: Akşam ilaçlarını, takviyelerini veya vitaminlerini almayı unutma 💊',
    questCelebrationTitle: 'Tüm Görevler Tamam! 🏆',
    questCelebrationBody: 'Bugün tüm hedeflerine ulaştın. Harika iş! 🌟',
    chatStarterWater: 'Günde ne kadar su içmeliyim?',
    chatStarterProtein: 'Yüksek proteinli yiyecekler nelerdir?',
    chatStarterCalories: 'Kaç kalori almam gerekiyor?',
    chatStarterSleep: 'Uyku kilo kaybını nasıl etkiler?',
    chatStarterFast: 'Aralıklı orucun faydaları nelerdir?',
    nudgeBreakfast: 'Kahvaltı zamanı — günün ilk öğününü kaydet!',
    nudgeLunch: 'Öğle yemeği vakti — kaydetmeyi unutma!',
    nudgeDinner: 'Akşam yemeği vakti — akşam öğününü kaydet.',
    nudgeActivity: 'Henüz aktivite kaydı yok — bir antrenman ekle!',
    profileNudgeTitle: 'Profilini tamamla',
    profileNudgeBody: 'Daha doğru sağlık önerileri için boy ve kilonu ekle.',
    profileNudgeAction: 'Şimdi tamamla',
    dailyQuests: 'Gunluk Gorevler',
    questLogMeal: 'Bir ogun kaydet',
    questDrinkWater: '8 bardak su ic',
    questDoActivity: 'Bir aktivite yap',
    questVoiceLog: 'Sesli gunluk kaydet',
    questCheckScore: 'Saglik skorunu kontrol et',
    questsCompleted: 'Tum gorevler tamamlandi!',
    questDataLoadFailed: 'Gorev verileri yuklenemedi',
    aiCoachTitle: 'Myora AI Koc',
    aiCoachAsk: 'Soru sor',
    aiCoachHint: 'Beslenme, egzersiz ve saglik konusunda yardimci olabilirim.',
    askAiDesc: 'AI saglik kocundan aninda cevap al',
    achievementEarned: 'Basarim kazanildi!',
    achievementsTitle: 'Basarimlar',
    achievementsEarned: 'Kazanilan',
    achievementsLocked: 'Kilitli',
    achievementsPoints: 'puan',
    widgetsTitle: 'Widgetlar',
    activeWidgetCount: 'Aktif widget sayisi',
    activeWidgetsOnHome: 'widget ana ekranda aktif',
    createNewWidget: 'Yeni Widget Olustur',
    dailyRecommendations: 'Gunluk Oneriler',
    calorieBalance: 'Kalori dengesi',
    calorieBalanceDesc: 'Bugun hedefe ulasmak icin yaklasik {{remainingCalories}} kcal kaldi.',
    waterGoal: 'Su hedefi',
    waterGoalDesc: 'Su tuketiminde {{waterProgress}}% seviyesindesin. Aksam icin 1-2 bardak ekle.',
    waterGlassesUnit: 'bardak',
    addWaterGlass: '+ 1 bardak (300 ml)',
    waterGoalReached: 'Hedefe ulaşıldı! Süper! 💧',
    proteinTracking: 'Protein takibi',
    proteinTrackingDesc: 'Protein hedefinin {{proteinProgress}}%\'ini tamamladin.',
    healthTracking: 'Saglik Takibi',
    devices: 'Cihazlar',
    connectWearables: 'Wearable bagla',
    fasting: 'Fasting',
    trackIntermittent: 'Aralikli oruc takibi',
    mealEntry: 'Ogun Kaydi',
    foodLog: 'Yemek',

    // Logger
    loggerTitle: 'Kayitlar',
    loggerSubtitle: 'Son kayitlarini burada takip et. Yeni kayit icin alttaki + butonunu kullan.',
    todayLoggingProgress: 'Bugunku Kayit Ilerlemesi',
    mealsLogged: 'Ogun',
    voiceEntries: 'Ses',
    activityLogged: 'Aktivite',
    documents: 'Belge',
    recentEntries: 'Son Kayitlar',
    recentFoodsTitle: 'Tekrar Kaydet',
    logAgain: 'Kaydet',
    foodRelogged: 'Öğün tekrar kaydedildi!',
    relogFailed: 'Öğün tekrar kaydedilemedi',
    justNow: 'Az once',
    minAgo: 'dk once',
    hrAgo: 'sa once',
    dayAgo: 'g once',
    min: 'dk',
    voiceEntry: 'Ses kaydi',
    todayCalories: 'Bugunku kalori',
    totalEntries: 'kayit',
    dataLoadFailed: 'Veriler yuklenemedi',
    entriesLoadFailed: 'Kayitlar yuklenemedi',

    // Coach hub
    coachTitle: 'Koc',
    coachSubtitle: 'AI destekli rehberlik merkezi',
    expertChat: 'Expert Chat',
    expertChatDesc: 'Bilimsel kaynaklarla kisisellestirilmis saglik danismanligi al.',
    boostDesc: 'Gunluk verilerine gore hizli iyilestirme ve motivasyon onerileri gor.',
    boost: 'Boost',

    // Analysis hub
    analysisTitle: 'Analiz',
    analysisSubtitle: 'Tum icgoru ve modullere tek merkezden erisim',
    insights: 'Icgoruler',
    ecosystem: 'Ekosistem',
    healthProfile: 'Saglik Profilim',
    healthProfileDesc: 'AI skor, BMI/BMR/TDEE ve kisisel planlar',
    wearableData: 'Wearable Verileri',
    wearableDataDesc: 'Nabiz, uyku, adim ve trendler',
    analyticsDesc: 'Haftalik/aylik ilerleme grafikleri',
    supplementStore: 'Takviye Magazasi',
    supplementStoreDesc: 'AI onerileri ve siparisler',
    community: 'Topluluk',
    communityDesc: 'Deneyim paylasimi ve soru-cevap',
    familyTracking: 'Aile Takibi',
    familyTrackingDesc: 'Yakinlar icin ilac/takviye takibi',

    // Auth extended
    authSubtitle: 'Saglikli yasaminizi takip etmeye baslayin',
    signInError: 'Giris Hatasi',
    signUpError: 'Kayit Hatasi',
    passwordMismatch: 'Sifreler eslasmiyor',
    accountCreated: 'Hesabiniz olusturuldu! Lutfen e-postanizi kontrol edin.',
    loginSuccess: 'Basariyla giris yaptiniz!',
    passwordRepeat: 'Sifre Tekrar',
    exampleEmail: 'ornek@email.com',
    passwordHint: 'En az 6 karakter, 1 harf ve 1 rakam',

    // Dashboard
    dashboard: 'Ana Sayfa',
    dailyGoals: 'Gunluk Hedefler',
    calories: 'Kalori',
    remaining: 'kaldi',
    protein_intake: 'Protein',
    water: 'Su',
    quickActions: 'Hizli Islemler',
    logFood: 'Yemek Kaydet',
    addMeal: 'Ogun Ekle',
    recordActivity: 'Aktivite Kaydet',

    voiceLog: 'Sesli Kayit',
    recentActivities: 'Son Aktiviteler',
    noRecentEntries: 'Yakin zamanda kayit yok',

    // Navigation
    home: 'Ana Sayfa',
    profile: 'Profil',
    analytics: 'Analitik',
    settings: 'Ayarlar',
    mainNavigation: 'Ana navigasyon',
    quickAddLabel: 'Hizli ekle',

    // Auth
    signIn: 'Giris Yap',
    signUp: 'Kayit Ol',
    email: 'E-posta',
    password: 'Sifre',
    confirmPassword: 'Sifreyi Onayla',
    dontHaveAccount: 'Hesabiniz yok mu?',
    alreadyHaveAccount: 'Zaten hesabiniz var mi?',
    signOut: 'Cikis Yap',
    signOutFailed: 'Cikis yapilamadi',

    // Onboarding
    onboardingWelcome: "Myora'ya Hos Geldiniz!",
    onboardingWelcomeDesc: 'Saglik yolculugunuzu birkac adimda kisisellestrelim.',
    onboardingFeature1: 'Yapay Zeka Destekli Analizler',
    onboardingFeature1Desc: 'Yapay zeka ile kisisellestirilmis saglik onerileri alin.',
    onboardingFeature2: 'Her Seyi Takip Edin',
    onboardingFeature2Desc: 'Beslenme, aktivite, uyku ve dahasi — tek bir yerde.',
    onboardingFeature3: 'Hedeflerinize Ulasin',
    onboardingFeature3Desc: 'Hedefler belirleyin ve ilerlemenizi her gun izleyin.',
    onboardingStep1Title: 'Hakkinizda',
    onboardingStep1Desc: 'Temel bilgiler saglik metriklerinizi hesaplamamiza yardimci olur.',
    onboardingGender: 'Cinsiyet',
    onboardingMale: 'Erkek',
    onboardingFemale: 'Kadin',
    onboardingOther: 'Diger',
    onboardingHeight: 'Boy (cm)',
    onboardingWeight: 'Kilo (kg)',
    onboardingBirthDate: 'Dogum Tarihi',
    onboardingStep2Title: 'Hedefiniz',
    onboardingStep2Desc: 'Neye odaklanmak istiyorsunuz?',
    onboardingGoalWeightLoss: 'Kilo Vermek',
    onboardingGoalMuscle: 'Kas Gelistirmek',
    onboardingGoalHealth: 'Saglikli Kalmak',
    onboardingGoalSleep: 'Daha Iyi Uyku',
    onboardingGoalStress: 'Stresi Azaltmak',
    onboardingStep3Title: 'Aktivite Seviyesi',
    onboardingStep3Desc: 'Normal bir gunde ne kadar aktifsiniz?',
    onboardingActivitySedentary: 'Hareketsiz',
    onboardingActivitySedentaryDesc: 'Cogunlukla oturarak (ofis isi)',
    onboardingActivityLight: 'Hafif Aktif',
    onboardingActivityLightDesc: 'Haftada 1-3 gun hafif egzersiz',
    onboardingActivityModerate: 'Orta Aktif',
    onboardingActivityModerateDesc: 'Haftada 3-5 gun orta egzersiz',
    onboardingActivityVery: 'Cok Aktif',
    onboardingActivityVeryDesc: 'Haftada 6-7 gun yogun egzersiz',
    onboardingNext: 'Ileri',
    onboardingBack: 'Geri',
    onboardingFinish: 'Baslayalim',
    onboardingSkip: 'Simdilik atla',
    onboardingStepOf: '/',

    // General
    save: 'Kaydet',
    cancel: 'Iptal',
    edit: 'Duzenle',
    delete: 'Sil',
    confirm: 'Onayla',
    loading: 'Yukleniyor...',
    error: 'Hata',
    success: 'Basarili',
    add: 'Ekle',
    adding: 'Ekleniyor...',
    remove: 'Kaldir',

    // NotFound
    pageNotFound: 'Bu sayfa bulunamadi.',
    goHome: 'Ana Sayfaya Don',

    // AppLayout
    exitAppConfirm: 'Uygulamadan cikmak istiyor musunuz?',

    // Activity Logger
    activityLogTitle: 'Aktivite Kaydet',
    activityLogSubtitle: 'Antrenman ve fiziksel aktivitelerinizi takip edin',
    newActivity: 'Yeni Aktivite',
    activityType: 'Aktivite Turu',
    selectActivityType: 'Aktivite turu secin',
    durationMinutes: 'Sure (dakika)',
    intensity: 'Yogunluk',
    selectIntensity: 'Yogunluk seviyesi secin',
    intensityLow: 'Dusuk',
    intensityModerate: 'Orta',
    intensityHigh: 'Yuksek',
    estimatedCalories: 'Tahmini Yakilan Kalori (opsiyonel)',
    notesOptional: 'Notlar (opsiyonel)',
    notesPlaceholder: 'Nasil hissettiniz? Gozlemleriniz...',
    saving: 'Kaydediliyor...',
    todaysActivities: 'Bugunku Aktiviteler',
    loadingActivities: 'Aktiviteler yukleniyor...',
    noActivitiesYet: 'Henuz aktivite kaydi yok',
    logFirstActivity: 'Ilk aktivitenizi yukaridan kaydedin',
    loggedSuccessfully: 'basariyla kaydedildi!',
    minutes: 'dakika',
    intensityLabel: 'yogunluk',
    activityTypeRequired: 'Aktivite turu seciniz',
    durationMinError: 'Sure en az 1 dakika olmali',

    // Blood Test Analysis
    bloodTest: 'Kan Tahlili',
    analyzeWithAi: 'Sonuclarinizi AI ile analiz edin',
    upload: 'Yukle',
    uploadNewTest: 'Yeni Tahlil Yukle',
    labNamePlaceholder: 'Laboratuvar adi',
    testResultsPlaceholder: 'Tahlil sonuclarini yapistirin veya OCR metnini girin...\nOrnek:\nGlukoz: 95 mg/dL\nHbA1c: 5.4%\nTSH: 2.1 mIU/L',
    analyzing: 'Analiz ediliyor...',
    analyze: 'Analiz Et',
    noBloodTestsYet: 'Henuz kan tahlili yok',
    uploadTestsForAi: 'Tahlil sonuclarinizi yukleyerek AI analizi alin',
    uploadTest: 'Tahlil Yukle',
    statusNormal: 'Normal',
    statusAttention: 'Dikkat',
    statusCritical: 'Kritik',
    statusHigh: 'Yuksek',
    aiSummary: 'AI Ozeti',
    ref: 'Ref',
    bloodTestUploaded: 'Kan tahlili basariyla yuklendi',
    bloodTestUploadFailed: 'Kan tahlili yuklenemedi',
    bloodTestsLoadFailed: 'Kan tahlilleri yuklenemedi',

    // Community
    communityTitle: 'Topluluk',
    communitySubtitle: 'Deneyimlerini paylas, birlikte buyu',
    share: 'Paylas',
    catGeneral: 'Genel',
    catNutrition: 'Beslenme',
    catExercise: 'Egzersiz',
    catQuestions: 'Sorular',
    catSuccessStories: 'Basari Hikayeleri',
    newPost: 'Yeni Paylasim',
    titlePlaceholder: 'Baslik',
    shareThoughts: 'Dusuncelerini paylas...',
    sharing: 'Paylasiliyor...',
    anonymous: 'Anonim',
    noPostsYet: 'Henuz paylasim yok',
    beFirstToPost: 'Ilk paylasimi sen yap!',
    postCreated: 'Paylasim olusturuldu',
    postCreateFailed: 'Paylasim olusturulamadi',
    postsLoadFailed: 'Paylasimlar yuklenemedi',
    likeFailed: 'Begeni islemi basarisiz',

    // Analytics
    statsAndAnalysis: 'Istatistikler & Analiz',
    detailedProgress: 'Detayli ilerleme takibi ve analiz',
    weeklyLog: 'Haftalik Log',
    last7Days: 'Son 7 gun',
    achievementCount: 'Basari',
    fastingDay: 'Oruc Gunu',
    thisMonth: 'Bu Ay',
    avgCalories: 'Ort. Kalori',
    daily: 'Gunluk',
    weeklyTrend: 'Haftalik Trend',
    macroDistribution: 'Makro Dagilimi',
    monthlyProgressTitle: 'Aylik Ilerleme',
    achievementsSection: 'Basarilar',
    notEnoughData: 'Henuz yeterli veri yok',
    noFoodRecords: 'Yemek kaydi bulunamadi',
    noFastingRecords: 'Henuz oruc kaydi yok',
    noAchievementDef: 'Basari tanimi bulunamadi',
    completed: 'Tamamlandi',
    proteinMacro: 'Protein',
    carbsMacro: 'Karbonhidrat',
    fatMacro: 'Yag',
    dayNames: 'Paz,Pzt,Sal,Car,Per,Cum,Cmt',
    monthNames: 'Oca,Sub,Mar,Nis,May,Haz,Tem,Agu,Eyl,Eki,Kas,Ara',

    // Expert Chat
    expertTitle: 'Expert',
    expertSubtitle: 'Bilimsel kaynaklara dayali saglik danismaniniz',
    welcomeMessage: 'Merhaba! Ben Expert, saglik danismaniniz. Bilimsel kaynaklara dayali, kisisellesirilmis saglik bilgileri sunmak icin buradayim. Nasil yardimci olabilirim?',
    errorFallback: 'Uzgunum, su anda yanit olusturamadim. Lutfen tekrar deneyin.',
    sources: 'Kaynaklar',
    askHealthQuestion: 'Saglik hakkinda bir soru sorun...',
    expertDisclaimer: 'Expert, bilimsel yayinlara dayali bilgi saglar. Tibbi tavsiye yerine gecmez.',

    // Voice Logger
    voiceRecording: 'Sesli Kayit',
    voiceRecordSubtitle: 'Saglik notlarinizi veya yemeklerinizi sesli kaydedin',
    healthLog: 'Saglik Gunlugu',
    foodRecord: 'Yemek Kaydi',
    recordingDone: 'Kayit tamamlandi!',
    recordingStarted: 'Kayit basladi!',
    micDenied: 'Mikrofon erisimi reddedildi. Lutfen mikrofon iznini verin ve tekrar deneyin.',
    micNotAccessible: 'Mikrofona erisilemedi',
    playbackFailed: 'Kayit oynatilamadi',
    textNeeded: 'Analiz icin metin gerekli. Lutfen konusun veya yazarak girin.',
    voiceFoodEntry: 'Sesli Yemek Kaydi',
    voiceHealthLog: 'Sesli Saglik Gunlugu',
    foodsAddedToLog: 'yemek kalori takibine eklendi!',
    analysisDoneAndSaved: 'Analiz tamamlandi ve kaydedildi!',
    savedWithError: 'Kayit kaydedildi (AI analiz sunucu hatasi)',
    enterText: 'Lutfen bir metin girin',
    recordingInProgress: 'Kayit devam ediyor...',
    recordingSaving: 'Kaydediliyor...',
    foodRecordPrompt: 'Bugun ne yediginizi anlatin, or: "Ogle yemeginde tavuk pilav yedim"',
    healthRecordPrompt: 'Bugun nasil hissediyorsunuz, saglik dusuncelerinizi paylasin',
    recordCompleteTime: 'Kayit tamamlandi',
    foodAnalyzeHint: "Analiz Et'e tiklayin, yemekleriniz otomatik tespit edilip kaydedilecek",
    healthAnalyzeHint: 'Dinleyin veya analiz edin',
    recordFoodVoice: 'Yemeklerinizi sesle kaydedin',
    readyToListen: 'Dinlemeye hazir',
    foodVoiceDesc: 'Fotograf cekmek yerine yediginiz yemekleri sesli olarak soyleyin',
    healthVoiceDesc: 'Mikrofona dokunarak gunluk saglik kaydinizi baslatin',
    speechNotSupported: 'Tarayiciniz ses tanimayidesteklemiyor. Kayittan sonra metin olarak girebilirsiniz.',
    recordFoodBtn: 'Yemek Kaydet',
    startRecordingBtn: 'Kayit Baslat',
    typeInstead: 'Yazarak Gir',
    stopRecordingBtn: 'Kaydi Durdur',
    play: 'Oynat',
    analyzeBtn: 'Analiz Et',
    typeYourFood: 'Yemeklerinizi Yazin',
    typeYourNote: 'Saglik Notunuzu Yazin',
    foodTypePlaceholder: 'Or: Ogle yemeginde tavuk pilav yedim, yaninda salata ve ayran vardi',
    healthTypePlaceholder: 'Or: Bugun kendimi yorgun hissediyorum, uyku kalitem dusuk...',
    analyzeAndSave: 'Analiz Et ve Kaydet',
    liveTranscription: 'Canli Transkripsiyon',
    speechNotAvailable: 'Ses tanima kullanilamiyor. Kaydinizi yazarak da girebilirsiniz:',
    typeRecording: 'Kaydinizi buraya yazin...',
    detectingFood: 'Yemekler tespit ediliyor...',
    analyzingHealthLog: 'Saglik kaydiniz analiz ediliyor...',
    foodDetectDesc: 'Sesinizdeki yemekler tanimlanip kalori hesaplaniyor',
    healthAnalyzeDesc: 'AI saglik bilgilerinizi isliyor',
    audioRecording: 'Ses Kaydi',
    aiAnalysisResults: 'AI Analiz Sonuclari',
    moodLabel: 'Ruh hali:',
    emotionLabel: 'Duygu:',
    keyTopics: 'Anahtar konular:',
    summaryLabel: 'Ozet:',
    recommendationsTitle: 'Oneriler',
    newRecording: 'Yeni Kayit Yap',
    neutral: 'Notr',

    // Interval Fasting
    intermittentFasting: 'Aralikli Oruc',
    fastingSubtitle: 'Saglikli yasam icin oruc takibi',
    currentFast: 'Mevcut Oruc',
    dayStreak: 'gun seri',
    timeRemaining: 'kalan sure',
    fastingComplete: 'tamamlandi!',
    progress: 'Ilerleme',
    startFast: 'Orucu Baslat',
    pauseFast: 'Duraklat',
    resumeFast: 'Devam Et',
    endFast: 'Bitir',
    fastingActive: 'Oruc aktif - Devam ediyorsunuz!',
    fastingChipLabel: 'Oruç',
    weeklySummaryTitle: '📊 Geçen Hafta Özeti',
    weeklySummaryMeals: 'Ort. kkal/gün',
    weeklySummaryActivities: 'Aktif gün',
    weeklySummaryAvgWater: 'Ort. bardak/gün',
    weeklySummaryOver: '{{n}} gün boyunca',
    fastingPlans: 'Oruc Planlari',
    fastingPlanBeginner: 'Baslangic icin ideal',
    fastingPlanIntermediate: 'Orta seviye',
    fastingPlanPopular: 'En populer',
    fastingPlanAdvanced: 'Ileri seviye',
    fastingPlanExpert: 'Uzman seviye',
    todayBenefits: 'Bugunun Faydalari',
    fatBurning: 'Yag Yakimi',
    metabolismBoosted: 'Metabolizma hizlandi',
    detox: 'Detoks',
    cellsRenewing: 'Hucreler yenileniyor',
    focus: 'Odak',
    mentalClarity: 'Mental netlik artiyor',
    fastingCongrats: 'Tebrikler! Oruc hedefinizi tamamladiniz!',
    fastingStarted: 'Oruc baslatildi! Basarilar',
    fastingStartFailed: 'Oruc baslatilamadi',
    fastingPaused: 'Oruc duraklatildi',
    fastingReset: 'Oruc sifirlandi',

    // Wearable Devices
    wearableDevicesTitle: 'Giyilebilir Cihazlar',
    wearableDevicesSubtitle: 'Saglik verilerinizi takip edin',
    bluetoothNote: 'Bluetooth cihaz senkronizasyonu yakinda eklenecek. Su anda cihaz yonetimi ve veri goruntuleme aktiftir.',
    addDevice: 'Cihaz Ekle',
    addNewDevice: 'Yeni Cihaz Ekle',
    connectSmartwatch: 'Akilli saatinizi veya fitness takipcinizi baglayin',
    selectDevice: 'Cihaz Secin',
    selectDevicePlaceholder: 'Bir cihaz secin',
    deviceName: 'Cihaz Adi',
    deviceNamePlaceholder: 'Orn: Benim Saatim',
    connectDevice: 'Cihazi Bagla',
    noDevicesYet: 'Henuz cihaz baglanmadi',
    addDeviceToTrack: 'Saglik verilerinizi takip etmek icin bir cihaz ekleyin',
    connected: 'Bagli',
    notConnected: 'Bagli Degil',
    disconnect: 'Baglanitiyi Kes',
    connect: 'Baglan',
    deviceSelectAndName: 'Lutfen cihaz ve isim secin',
    deviceAdded: 'Cihaz basariyla eklendi',
    deviceAddFailed: 'Cihaz eklenirken hata olustu',
    deviceConnected: 'Cihaz baglandi',
    deviceDisconnected: 'Cihaz baglantisi kesildi',
    connectionUpdateFailed: 'Baglanti durumu guncellenemedi',
    deviceRemoved: 'Cihaz kaldirildi',
    deviceRemoveFailed: 'Cihaz kaldirilirken hata olustu',

    // Supplement Store
    supplementTitle: 'Takviye Gida',
    supplementSubtitle: 'Size ozel oneriler & siparis',
    recommendationsTab: 'Oneriler',
    storeTab: 'Magaza',
    ordersTab: 'Siparisler',
    noRecommendationsYet: 'Henuz oneri yok',
    recommendationsDesc: 'Kan tahlili veya saglik profiliniz analiz edildiginde oneriler olusturulacak',
    highPriority: 'Yuksek',
    mediumPriority: 'Orta',
    lowPriority: 'Dusuk',
    priority: 'Oncelik',
    dosage: 'Dozaj:',
    all: 'Tumu',
    orderNow: 'Siparis Ver',
    noCategoryProducts: 'Bu kategoride henuz urun yok',
    noOrdersYet: 'Henuz siparis yok',
    recStatusUpdated: 'Oneri durumu guncellendi',
    recStatusFailed: 'Oneri durumu guncellenemedi',
    recsLoadFailed: 'Oneriler yuklenemedi',
    catVitamins: 'Vitaminler',
    catMinerals: 'Mineraller',
    catAminoAcids: 'Amino Asitler',
    catHerbal: 'Bitkisel',
    catProbiotics: 'Probiyotikler',
    catOmega: 'Omega',
    catProtein: 'Protein',

    // Family Tracking
    familyTrackingTitle: 'Aile Takibi',
    familyTrackingSubtitleHeader: 'Yakinlarinizin sagligini takip edin',
    medicationTracking: 'Ilac ve takviye takibi',
    familyMember: 'Aile Uyesi',
    noFamilyMembers: 'Henuz aile uyesi yok',
    addFamilyDesc: 'Yakinlarinizi ekleyerek sagliklarini takip edin',
    addFamilyMember: 'Aile Uyesi Ekle',
    name: 'Isim',
    todayAdherence: 'Bugunku Uyum',
    medicationsTaken: 'ilac alindi',
    medicationsAndSupplements: 'Ilaclar & Takviyeler',
    noMedicationsYet: 'Henuz ilac eklenmedi',
    addMedicationDesc: 'Ilac ve takviye ekleyerek takibi baslatin',
    addMedication: 'Ilac Ekle',
    medicationName: 'Ilac/Takviye adi',
    addMedicationSupplement: 'Ilac/Takviye Ekle',
    relParent: 'Ebeveyn',
    relChild: 'Cocuk',
    relSpouse: 'Es',
    relSibling: 'Kardes',
    relGrandparent: 'Buyuk Ebeveyn',
    relOther: 'Diger',
    familyMemberAdded: 'Aile uyesi eklendi',
    familyMemberAddFailed: 'Aile uyesi eklenemedi',
    familyLoadFailed: 'Aile uyeleri yuklenemedi',
    medicationAdded: 'Ilac eklendi',
    medicationAddFailed: 'Ilac eklenemedi',
    medicationLogFailed: 'Ilac kaydi basarisiz',

    // User Profile
    profileInfo: 'Profil Bilgileri',
    displayName: 'Gorunen Ad',
    yourName: 'Adiniz',
    dateOfBirth: 'Dogum Tarihi',
    heightCm: 'Boy (cm)',
    weightKg: 'Kilo (kg)',
    activityLevel: 'Aktivite Seviyesi',
    selectActivityLevel: 'Aktivite seviyenizi secin',
    sedentary: 'Hareketsiz',
    lightlyActive: 'Hafif Aktif',
    moderatelyActive: 'Orta Aktif',
    active: 'Aktif',
    veryActive: 'Cok Aktif',
    bmi: 'Vucut Kitle Indeksi (BMI)',
    bmiUnderweight: 'Zayif',
    bmiNormal: 'Normal',
    bmiOverweight: 'Fazla Kilolu',
    bmiObese: 'Obez',
    profileUpdated: 'Profil bilgileriniz guncellendi',
    profileUpdateFailed: 'Profil guncellenirken hata olustu',
    signOutLabel: 'Cikis',
    signOutError: 'Cikis yapilirken hata olustu',
  },
} as const;

type TranslationStrings = { [K in keyof typeof translations.en]: string };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: TranslationStrings;
  locale: string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    try {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && ['en', 'tr'].includes(savedLanguage)) {
        setLanguage(savedLanguage);
      }
    } catch { /* localStorage unavailable */ }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    try { localStorage.setItem('language', lang); } catch { /* noop */ }
  };

  // Merge Turkish over English so any untranslated key falls back to English
  const t: TranslationStrings = language === 'tr'
    ? { ...translations.en, ...translations.tr } as unknown as TranslationStrings
    : translations.en as unknown as TranslationStrings;

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage: handleSetLanguage,
        t,
        locale: language === 'tr' ? 'tr-TR' : 'en-US',
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
